---
# Create gitea Users
- name: create gitea admin user '{{ gitea_admin_user }}'
  uri:
    url: http://{{ gitea_route }}/user/sign_up
    method: POST
    body: "user_name={{ gitea_admin_user }}&password={{ gitea_admin_password }}&&retype={{ gitea_admin_password }}&&email={{ gitea_admin_user }}@gitea.com"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: 302,200

- name: check if user '{{ gitea_user }}' exists
  uri:
    url: http://{{ gitea_route }}/api/v1/users/{{ gitea_user }}
    user: "{{ gitea_admin_user }}"
    password: "{{ gitea_admin_password }}"
    force_basic_auth: true
    status_code: 200,404
  register: user_result

- name: create gitea user '{{ gitea_user }}'
  uri:
    url: http://{{ gitea_route }}/api/v1/admin/users
    method: POST
    body: "{'login_name': '{{ gitea_user }}', 'username': '{{ gitea_user }}', 'email': '{{ gitea_user }}@gitea.com', 'password': '{{ gitea_password }}'}"
    body_format: json
    user: "{{ gitea_admin_user }}"
    password: "{{ gitea_admin_password }}"
    status_code: 200,201
    force_basic_auth: true
  when: user_result.status != 200

- name: generate gitea users
  uri:
    url: http://{{ gitea_route }}/api/v1/admin/users
    method: POST
    body: "{'login_name': '{{ item }}', 'username': '{{ item }}', 'email': '{{ item }}@gitea.com', 'password': '{{ gitea_password }}'}"
    body_format: json
    user: "{{ gitea_admin_user }}"
    password: "{{ gitea_admin_password }}"
    status_code: 200,201
    force_basic_auth: true
  ignore_errors: true
  with_sequence: start=0 end={{ gitea_generate_user_count }} format="{{ gitea_generate_user_format }}"
  when: gitea_generate_user_count > 0
