---
## Deploy Gitea Git Server
- name: deploy gitea from template (persistent)
  shell: |
    {{ openshift_cli }} new-app -f https://raw.githubusercontent.com/wkulhanek/docker-openshift-gitea/master/openshift/gitea-persistent-template.yaml \
        --param=HOSTNAME={{ gitea_route }} \
        --param=GITEA_VERSION={{ gitea_image_version }} \
        --param=SKIP_TLS_VERIFY={{ skip_tls_verify }} \
        --param=APPLICATION_NAME={{ gitea_service_name }} \
        -n {{ project_name }}
  when: not ephemeral|bool

- name: deploy gitea from template (ephemeral)
  shell: |
    {{ openshift_cli }} new-app -f https://raw.githubusercontent.com/wkulhanek/docker-openshift-gitea/master/openshift/gitea-ephemeral-template.yaml \
        --param=HOSTNAME={{ gitea_route }} \
        --param=GITEA_VERSION={{ gitea_image_version }} \
        --param=SKIP_TLS_VERIFY={{ skip_tls_verify }} \
        --param=APPLICATION_NAME={{ gitea_service_name }} \
        -n {{ project_name }}
  when: ephemeral|bool

- name: set cpu and mem 
  shell: "{{ openshift_cli }} set resources dc/{{ gitea_service_name }} --limits=cpu={{ max_cpu }},memory={{ max_mem }} --requests=cpu={{ min_cpu }},memory={{ min_mem }} -n {{ project_name }}"

- name: wait for gitea postgresql to be running
  uri:
    url: http://{{ gitea_route }}
    status_code: 200
  register: result
  until: result.status == 200
  retries: "{{ gitea_deploy_retry_count }}"
  delay: "{{ gitea_deploy_retry_delay }}"
